name: Select Configurations

on: workflow_dispatch

jobs:
  test_config:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - description: latest
            python-version: 3.13.10
            rf-version: 7.4.1
            selenium-version:  4.39.0
            browser: chrome
          - description: previous
            python-version: 3.12.12
            rf-version: 7.3.2
            selenium-version: 4.38.0
            browser: firefox

    steps:
    - uses: actions/checkout@v4
    - name: Configuration Description
      run: |
        echo "${{ matrix.config.description }} configuration"
        echo "Testing with RF v${{ matrix.config.rf-version }}, Selenium v${{ matrix.config.selenium-version}}, Python v${{ matrix.config.python-version }} under ${{ matrix.config.browser }}"
    - name: Set up Python ${{ matrix.config.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.config.python-version }}
    - name: Setup ${{ matrix.config.browser }} browser
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 138
        install-dependencies: true
        install-chromedriver: true
      id: setup-chrome
    - run: |
        echo Installed chromium version: ${{ steps.setup-chrome.outputs.chrome-version }}
        ${{ steps.setup-chrome.outputs.chrome-path }} --version
    - name: Setup firefox
      id: setup-firefox
      uses: browser-actions/setup-firefox@v1
      with:
        firefox-version: latest
    - run: |
        echo Installed firefox versions: ${{ steps.setup-firefox.outputs.firefox-version }}
        ${{ steps.setup-firefox.outputs.firefox-path }} --version
    - name: Start xvfb
      run: |
        export DISPLAY=:99.0
        Xvfb -ac :99 -screen 0 1280x1024x16 > /dev/null 2>&1 &
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Install Seleninum v${{ matrix.config.selenium-version }}
      run: |
        pip install --upgrade selenium==${{ matrix.config.selenium-version }}
    - name: Install RF ${{ matrix.config.rf-version }}
      run: |
        pip install -U --pre robotframework==${{ matrix.config.rf-version }}
    - name: Install drivers via selenium-manager
      run: |
        SELENIUM_MANAGER_EXE=$(python -c 'from selenium.webdriver.common.selenium_manager import SeleniumManager; sm=SeleniumManager(); print(f"{str(sm._get_binary())}")')
        echo "$SELENIUM_MANAGER_EXE"
        echo "WEBDRIVERPATH=$($SELENIUM_MANAGER_EXE --browser chrome --debug | awk '/INFO[[:space:]]Driver path:/ {print $NF;exit}')" >> "$GITHUB_ENV"
        echo "$WEBDRIVERPATH"

    - name: Run tests under specified config
      run: |
        xvfb-run --auto-servernum python atest/run.py --zip ${{ matrix.config.browser }}

    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: sl_$${{ matrix.config.python-version }}_$${{ matrix.config.rf-version }}_$${{ matrix.config.selenium-version }}_$${{ matrix.config.browser }}
        path: atest/zip_results
        overwrite: true